Добавлен основной функционал.
Kalyanova/MovieLookup pull request #1
Opened 2018-08-17 14:47 UTC by Kalyanova

2018-08-18 09:29 UTC, aivanovski requested changes
Я выделил жирным критичные моменты, остальные коментарии носят скорее рекомендательный характер.

2018-08-18 09:29 UTC, aivanovski commented on app/src/main/java/by/paranoidandroid/movielookup/activities/MainActivity.java
> +    View.OnClickListener btnListener = view -> {
Нельзя ли код в btnListener разделить на какие-то более мелкие куски? Просто в нем очень много всего и сразу. Также лучше выносить нетворк запросы в отдельные сущности. Можно например паттерном репозиторий воспользоваться для этого.
В общем этот участок кода можно сделать более линейным, читаться он будет лучше. Например, я бы сделал вот так:

    imageBtn.setOnClickListener(view -> onLookUpButtonClicked());
    private void onLookUpButtonClicked() {
        hideKeyboard();
        //... showProgressBar() or something else
        sendGetMoviesRequest();
    }

    private void sendGetMoviesRequest() {
        moviesRepository.getMovies(movies -> onGetMoviesFinished(movies),
                errorMessage -> onGetMoviesFailed(errorMessage));
    }

    private void onGetMoviesFinished(List<Movie> movies) {
        //.... change view visibility and etc.
        setAdapterItems(movies);
    }

    private void setAdapterItems(List<Movie> movies) {
        //...
    }

    private void onGetMoviesFailed(String erroeMessage) {
        //....
    }

2018-08-18 09:29 UTC, aivanovski commented on app/src/main/java/by/paranoidandroid/movielookup/adapters/RecyclerViewAdapter.java
> +public class RecyclerViewAdapter extends RecyclerView.Adapter<RecyclerViewAdapter.ViewHolder> {
**Если Adapter предназначен для отображения объектов класса Movie, то лучше его назвать MoviesAdapter или как-то так, чтобы было понятно какие объекты он отображает.**

2018-08-18 09:29 UTC, aivanovski commented on app/src/main/java/by/paranoidandroid/movielookup/activities/MainActivity.java
> +                            recyclerView.setAdapter(new RecyclerViewAdapter(MainActivity.this, movies));
**Не нужно создавать новый adapter для RecyclerView каждый раз, когда хочешь отобразить новые элементы. Можно создать переменную adapter и в нее записать RecyclerViewAdapter. Если нужно отобразить новые элементы, делаем вот так:**
`adapter.setItems(newItems);`
`adapter.notifyDataSetChanged();`

**Вообще ключевая идея RecyclerView - это переиспользование View с помощью RecyclerView.Adapter. Если каждый раз, когда необходимо отобразить новые элементы, создавать новый адаптер, то эта ключевая идея теряется.**

2018-08-18 09:29 UTC, aivanovski commented on app/src/main/java/by/paranoidandroid/movielookup/activities/MainActivity.java
> +            recyclerView.setAdapter(new RecyclerViewAdapter(MainActivity.this, movies));
**Аналогичная проблема с адаптером.**

2018-08-18 09:29 UTC, aivanovski commented on app/src/main/java/by/paranoidandroid/movielookup/common/MyApplication.java
> +public class MyApplication extends Application {
Возможно для домашек и так сойдет, но мне кажется объектам связанным с network частью не место в классе Application. Я бы их вынес в репозиторий или пусть даже в какой-нибудь network-manager. Безусловно создание объектов Manger-ов не очень хорошо, с эстетической точки зрения, но уж лучше с ним, чем так)

2018-08-20 00:39 UTC, Kalyanova commented
Добавление основного функционала (черновой вариант).

2018-08-20 00:40 UTC, Kalyanova commented
Добавление основного функционала (черновой вариант).

2018-08-20 00:44 UTC, merged